version: '1'

services:
  - type: web
    name: luxorlms-app
    env: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t luxorlms-app .
    startCommand: dotnet LuxorLMS.Identity.Api.dll
